require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommentsController do

  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:body => "Test Body"}
  end

  before(:each) do
    @attr = { :name => "Test Group",
              :about => "We're a Group!"}

    @user = Factory(:confirmed_user)
    test_sign_in @user
    @group = @user.created_groups.create(@attr)
    @todo = @user.created_todos.create(:title => "SOMETHING")
    @group.todos << @todo
    @user.share(@group, @todo)
  end

  describe "POST create" do
    describe "permissions" do
      it "should not create a comment if not logged in" do
        sign_out @user
        expect {
          post :create, :comment => valid_attributes, :todo => @todo, :group => @group
        }.to_not change(Comment, :count).by(1)
      end

      it "should not create a comment if not a member" do
        @user = Factory(:confirmed_user)
        test_sign_in @user
        expect {
          post :create, :comment => valid_attributes, :todo => @todo, :group => @group
        }.to_not change(Comment, :count).by(1)
      end
    end

    describe "with valid params" do
      it "creates a new Comment" do
        expect {
          post :create, :comment => valid_attributes, :todo => @todo, :group => @group
        }.to change(Comment, :count).by(1)
      end

      it "assigns a newly created comment as @comment" do
        post :create, :comment => valid_attributes, :todo => @todo, :group => @group
        assigns(:comment).should be_a(Comment)
        assigns(:comment).should be_persisted
      end

      it "redirects to the todo" do
        post :create, :comment => valid_attributes, :todo => @todo, :group => @group
        response.should redirect_to(group_todo_path @group, @todo )
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comment as @comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :create, :comment => {}, :todo => @todo, :group => @group
        assigns(:comment).should be_a_new(Comment)
      end

      it "re-renders the todos/show template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :create, :comment => {}, :todo => @todo, :group => @group
        response.should render_template('todos/show')
      end
    end
  end

  describe "POST update" do
    describe "permissions" do
      it "should not update a comment if not logged in" do
        comment = @user.comments.create! valid_attributes
        sign_out @user
        post :update, :id => comment.id, :comment => {:body => "hmm"}, :todo => @todo, :group => @group
        Comment.any_instance.should_not_receive(:update_attributes).with({'these' => 'params'})
      end

      it "should not update a comment if not the creator" do
        comment = @user.comments.create! valid_attributes
        @user = Factory :confirmed_user
        test_sign_in @user
        post :update, :id => comment.id, :comment => {'these' => 'params'}, :todo => @todo, :group => @group
        Comment.any_instance.should_not_receive(:update_attributes).with({'these' => 'params'})
      end
    end

  describe "with valid params" do
      it "updates the requested comment" do
        comment = @user.comments.create! valid_attributes
        # Assuming there are no other comments in the database, this
        # specifies that the Comment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        post :update, :id => comment.id, :comment => {'these' => 'params'}, :todo => @todo, :group => @group
      end

      it "assigns the requested comment as @comment" do
        comment = @user.comments.create! valid_attributes
        post :update, :id => comment.id, :comment => valid_attributes, :todo => @todo, :group => @group
        assigns(:comment).should eq(comment)
      end

    end

    describe "with invalid params" do
      it "assigns the comment as @comment" do
        comment = @user.comments.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :update, :id => comment.id.to_s, :comment => {}, :todo => @todo, :group => @group
        assigns(:comment).should eq(comment)
      end

    end
  end

end
